services:
  postgres:
    container_name: uber-driving
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: jau123
      POSTGRES_USER: jau
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432